// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.karoid.rounded-theme",
    "name": "Rounded Theme",
    "description": "This plugin provides a rounded theme for Mattermost.",
    "homepage_url": "https://github.com/Karoid/mattermost-plugin-rounded-theme",
    "support_url": "https://github.com/Karoid/mattermost-plugin-rounded-theme/issues",
    "icon_path": "assets/rounded-theme.svg",
    "version": "0.0.2",
    "min_server_version": "6.2.1",
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
